# Base Image
FROM node:18 AS build

# Set working directory 
WORKDIR /usr/src/app

# Copy package files and install dependencies
COPY package*.json ./     
# Only copy package files first for caching dependencies 

RUN npm install

# Copy the rest of the React app
COPY . ./
# copy everything frm the 'webapp' folder to the container

# Build the React app
RUN npm run bui


# Serve stage - Using Nginx to serve the built app 
FROM nginx:1.21-alpine

# Copt  the React build output to Nginx's HTML directory 
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Expose Nginx default port
EXPOSE 80

# Start Nginx Server
CMD ["nginx", "-g", "daemon off;"]