# Base Image
FROM node:18

# Set working directory
WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./
RUN npm install

# Copy source files
COPY . .

# Expose the application's port
EXPOSE 5000

# Start the application 
CMD ["npm", "start"]