
name: API CI/CD

on:
    push:
        paths:
            - 'api/**'
        branches:
            - main
            

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '18.x'  # or use the latest stable version 

            - name: Install dependencies
              working-directory: ./api
              run: npm install

            - name: Run tests
              working-directory: ./api
              run: npm test

            - name: Build API 
              working-directory: ./api
              run: npm run build   # only if you have a build script

            - name: Log in to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v1

            - name: Build and Push Docker Image to Amazon ECR 
              env: 
                ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}
                ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
                IMAGE_TAG: latest
              run: |
                docker tag e-commerce:latest 026956291686.dkr.ecr.us-east-1.amazonaws.com/e-commerce:latest ./api
                docker push 026956291686.dkr.ecr.us-east-1.amazonaws.com/e-commerce:latest

            - name: Deploy to ECS
              uses: aws-actions/amazon-ecs-deploy-task-definition@v1
              with:
                task-definition: ecs-task-definition.json
                service: ${{ secrets.ECS_SERVICE }}
                cluster: ${{ secrets.ECR_CLUSTER }}
                wait-for-service-stability: true


